server:
  port: 8083


spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/Microservices
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  application:
    name: INVENTORY-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate: dialect :org.hibernate.dialect.PostgreSQLDialect




